name: GitHub Pages Deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Stamp release version
        run: VERSION=${{github.event.release.tag_name}} npm run stamp-version
      - name: Perform production build
        run: npm run build
      - name: Perform unit/integration tests
        run: npm run test
      - name: Deploy build to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: build
